Fix #5, Use OS_stat instead of OS_OpenCreate to verify file existence
nasa/SC pull request #81
Opened 2023-03-21 11:43 UTC by thnkslprpt

**Checklist**
* [x] I reviewed the [Contributing Guide](https://github.com/nasa/osal/blob/main/CONTRIBUTING.md).
* [x] I signed and emailed the appropriate [Contributor License Agreement](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) to GSFC-SoftwareRelease@mail.nasa.gov and copied cfs-program@lists.nasa.gov.

**Describe the contribution**
Fixes #5 
Call to `OS_OpenCreate()` in the `SC_LoadDefaultTables()` function converted to `OS_stat()`.

**Testing performed**
GitHub CI actions (incl. Build + Run, Unit Tests etc.) all passing successfully.

**Expected behavior changes**
Simplifies function and eases future maintenance.

**Contributor Info**
Avi Weiss @thnkslprpt

2023-09-29 14:18 UTC, jphickey requested changes
I'm not convinced this check should even be in there at all - no matter which function is used, its a race condition, due to the difference between the time of check and time of use.  

That is,  `CFE_TBL_Load()` will open the file again, and it should handle the error if it is not able to open it.  SC should just check for that possible result - it shouldn't do its own check to avoid that result, because any such attempt would be incomplete and a race condition.

As this change set stands right now, while `OS_stat()` is lighter weight, it only verifies that the file exists, it does not verify that the file is readable.

I think we should simplify this, and remove this extra check.

2023-10-02 03:52 UTC, thnkslprpt commented
> I'm not convinced this check should even be in there at all...

Great!
Updated.

2023-10-05 15:21 UTC, jphickey approved these changes
I like this simplification, but we need to check if this affects any of the build verification tests.  

I think we should merge it but we need to note this may need a corresponding test update to go with it.

2024-01-24 15:59 UTC, jphickey commented
Thanks for the update, I still think we should merge this one.  Will bring it up at the next review.

2024-01-25 19:50 UTC, merged